### ISSUE TITLE
feature request: expose reencrypt as a subcommand

### ISSUE THREAD

**Issue by tekumara** [FiloSottile/passage#37] opened 2023-01-12 19:53 UTC
When copying/moving to a new path passage will reencrypt.

Would be nice to expose a reencrypt in place subcommand that could be used to rotate the keys used for encryption (eg: in the case they are leaked.

**Comment by remko** [comment] 2023-02-05 18:15
Is this a duplicate of #13 ?

**Comment by FiloSottile** [comment] 2023-02-07 13:19
Yep, I think that's #13 but let me know if it doesn't seem to fit.

**Closed by FiloSottile** 2023-02-07 13:19 UTC
