### ISSUE TITLE
Best way to add a new yubikey to the store?

### ISSUE THREAD

**Issue by kfken** [FiloSottile/passage#23] opened 2022-10-10 00:12 UTC
Now that `age-plugin-yubikey` supports multiple keys, what's the best way to add a new yubikey (for example, a backup) to the passage store?  I added my new key to the existing identities and .age-recipients and then copied:

```
passage cp path/to/secret  new/path/to/secret
```

It's a bit cumbersome and sort of messes up the paths in the store.  Is this the only option, or is there a better one I haven't considered?

@str4d

**Comment by FiloSottile** [comment] 2022-12-27 12:10
Duplicate of #13. I need to implement re-encryption at some point.

**Closed by FiloSottile** 2022-12-27 12:10 UTC
