### ISSUE TITLE
Feature Request - ability to rekey all secrets

### ISSUE THREAD

**Issue by peterhoeg** [FiloSottile/passage#20] opened 2022-09-14 09:57 UTC
It would be great to have the option to easily rekey all secrets if there are changes to the recipients.

`agenix` which is a mechanism to deploy secrets to hosts that uses age has this option, which is very convenient.

**Comment by FiloSottile** [comment] 2022-12-27 12:13
Duplicate of #13

**Closed by FiloSottile** 2022-12-27 12:13 UTC
